/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estimador;

/**
 *
 * @author rogelio
 */
public class puntos extends javax.swing.JFrame {

    /**
     * Creates new form puntos
     */
    public puntos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        parametros = new javax.swing.JLabel();
        complejidad = new javax.swing.JLabel();
        significativos = new javax.swing.JLabel();
        baja = new javax.swing.JLabel();
        media = new javax.swing.JLabel();
        alta = new javax.swing.JLabel();
        entradas = new javax.swing.JLabel();
        salidad = new javax.swing.JLabel();
        archivos_l = new javax.swing.JLabel();
        archivos_i = new javax.swing.JLabel();
        consultas = new javax.swing.JLabel();
        panel_co = new javax.swing.JPanel();
        e_b = new javax.swing.JTextField();
        s_b = new javax.swing.JTextField();
        l_b = new javax.swing.JTextField();
        i_b = new javax.swing.JTextField();
        e_m = new javax.swing.JTextField();
        s_m = new javax.swing.JTextField();
        l_m = new javax.swing.JTextField();
        i_m = new javax.swing.JTextField();
        e_a = new javax.swing.JTextField();
        s_a = new javax.swing.JTextField();
        l_a = new javax.swing.JTextField();
        i_a = new javax.swing.JTextField();
        c_a = new javax.swing.JTextField();
        c_m = new javax.swing.JTextField();
        c_b = new javax.swing.JTextField();
        panel_leng = new javax.swing.JPanel();
        lenguaje_de = new javax.swing.JLabel();
        lenguaje = new javax.swing.JComboBox<>();
        otro = new javax.swing.JTextField();
        panel_carac = new javax.swing.JPanel();
        caracteristicas = new javax.swing.JLabel();
        l_c1 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        l_c2 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        l_c3 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox<>();
        l_c4 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox<>();
        l_c6 = new javax.swing.JLabel();
        c6 = new javax.swing.JComboBox<>();
        l_c7 = new javax.swing.JLabel();
        c7 = new javax.swing.JComboBox<>();
        l_c8 = new javax.swing.JLabel();
        c8 = new javax.swing.JComboBox<>();
        l_c9 = new javax.swing.JLabel();
        c9 = new javax.swing.JComboBox<>();
        l_c5 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox<>();
        l_c10 = new javax.swing.JLabel();
        c10 = new javax.swing.JComboBox<>();
        c14 = new javax.swing.JComboBox<>();
        l_c14 = new javax.swing.JLabel();
        c13 = new javax.swing.JComboBox<>();
        l_c13 = new javax.swing.JLabel();
        l_c12 = new javax.swing.JLabel();
        c12 = new javax.swing.JComboBox<>();
        c11 = new javax.swing.JComboBox<>();
        l_c11 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        panel_result = new javax.swing.JPanel();
        result = new javax.swing.JLabel();
        pf_s = new javax.swing.JLabel();
        pfs = new javax.swing.JTextField();
        puntos_aj = new javax.swing.JLabel();
        fc = new javax.swing.JTextField();
        factor_c = new javax.swing.JLabel();
        pfa = new javax.swing.JTextField();
        lines = new javax.swing.JLabel();
        ldc = new javax.swing.JTextField();
        miles = new javax.swing.JLabel();
        kldc = new javax.swing.JTextField();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Titulo.setText("Puntos de Función");

        parametros.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        parametros.setText("Parametros");

        complejidad.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        complejidad.setText("Complejidad");

        significativos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        significativos.setText("Significativos");

        baja.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        baja.setText("Baja");

        media.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        media.setText("Media");

        alta.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        alta.setText("Alta");

        entradas.setText("Entradas externas");

        salidad.setText("Salidas externas");

        archivos_l.setText("Archivos lógicos");

        archivos_i.setText("Archivos de interfaz");

        consultas.setText("Consultas");

        e_b.setText("0");
        e_b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                e_bFocusLost(evt);
            }
        });
        e_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_bActionPerformed(evt);
            }
        });

        s_b.setText("0");

        l_b.setText("0");

        i_b.setText("0");

        e_m.setText("0");
        e_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_mActionPerformed(evt);
            }
        });

        s_m.setText("0");

        l_m.setText("0");

        i_m.setText("0");

        e_a.setText("0");
        e_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_aActionPerformed(evt);
            }
        });

        s_a.setText("0");

        l_a.setText("0");

        i_a.setText("0");

        c_a.setText("0");

        c_m.setText("0");

        c_b.setText("0");

        javax.swing.GroupLayout panel_coLayout = new javax.swing.GroupLayout(panel_co);
        panel_co.setLayout(panel_coLayout);
        panel_coLayout.setHorizontalGroup(
            panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_coLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_b, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(i_b, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_b)
                    .addComponent(e_b)
                    .addComponent(s_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_m, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(i_m, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_m)
                    .addComponent(e_m)
                    .addComponent(s_m))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(i_a)
                            .addComponent(l_a, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_a, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s_a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(c_a))
                .addContainerGap())
        );
        panel_coLayout.setVerticalGroup(
            panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_coLayout.createSequentialGroup()
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addComponent(e_b, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addComponent(e_m, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addComponent(e_a, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(c_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        lenguaje_de.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lenguaje_de.setText("Lenguaje de Programación");

        lenguaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4GL", "Ada 83", "Ada 95", "APL", "BASIC - compilado","BASIC - interpretado", "BASIC ANSI/Quick/Turbo", "C","C++", "Cobol ANSI 85","Delphi 1","Ensamblador","Ensamblador (Macro)","Forth","Fortran 77","FoxPro 2.5","Generador de informes","Hoja de calculo","Java","Modula 2","Oracle","Oracle 2000","Paradox","Pascal","Pacal Turbo 5","Power Builder","Prolog","Visual Basic 3","Visual C++","Visual Cobol"}));
        lenguaje.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lenguaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lenguajeItemStateChanged(evt);
            }
        });
        lenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenguajeActionPerformed(evt);
            }
        });

        otro.setEditable(false);
        otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_lengLayout = new javax.swing.GroupLayout(panel_leng);
        panel_leng.setLayout(panel_lengLayout);
        panel_lengLayout.setHorizontalGroup(
            panel_lengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lengLayout.createSequentialGroup()
                .addGroup(panel_lengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_lengLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lenguaje_de))
                    .addGroup(panel_lengLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(otro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        panel_lengLayout.setVerticalGroup(
            panel_lengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lengLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lenguaje_de)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_lengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        caracteristicas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        caracteristicas.setText("Caracteristicas");

        l_c1.setText("C1");

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });

        l_c2.setText("C2");

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c3.setText("C3");

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c4.setText("C4");

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c6.setText("C6");

        c6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c7.setText("C7");

        c7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c8.setText("C8");

        c8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c9.setText("C9");

        c9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c5.setText("C5");

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c10.setText("C10");

        c10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        c14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c14.setText("C14");

        c13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c13.setText("C13");

        l_c12.setText("C12");

        c12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        c11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));

        l_c11.setText("C11");

        javax.swing.GroupLayout panel_caracLayout = new javax.swing.GroupLayout(panel_carac);
        panel_carac.setLayout(panel_caracLayout);
        panel_caracLayout.setHorizontalGroup(
            panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_caracLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_caracLayout.createSequentialGroup()
                        .addComponent(caracteristicas)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_caracLayout.createSequentialGroup()
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_caracLayout.createSequentialGroup()
                                .addComponent(l_c4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_c9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_caracLayout.createSequentialGroup()
                                    .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_caracLayout.createSequentialGroup()
                                            .addComponent(l_c2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel_caracLayout.createSequentialGroup()
                                            .addComponent(l_c3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_caracLayout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(l_c8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_caracLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(l_c7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(panel_caracLayout.createSequentialGroup()
                                    .addComponent(l_c1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(l_c6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_caracLayout.createSequentialGroup()
                                .addComponent(l_c5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_c10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_caracLayout.createSequentialGroup()
                                .addComponent(l_c14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_caracLayout.createSequentialGroup()
                                        .addComponent(l_c13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_caracLayout.createSequentialGroup()
                                        .addComponent(l_c12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panel_caracLayout.createSequentialGroup()
                                    .addComponent(l_c11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61))))
        );
        panel_caracLayout.setVerticalGroup(
            panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_caracLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caracteristicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_caracLayout.createSequentialGroup()
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c1)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_c6)
                            .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_caracLayout.createSequentialGroup()
                                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_c2)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_c3)
                                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_caracLayout.createSequentialGroup()
                                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_c7)
                                    .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_c8)
                                    .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c4)
                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_c9)
                            .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c5)
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_c10)))
                    .addGroup(panel_caracLayout.createSequentialGroup()
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c11)
                            .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c12)
                            .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c13)
                            .addComponent(c13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_caracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_c14)
                            .addComponent(c14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        result.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        result.setText("Resultados");

        pf_s.setText("Puntos de Función Sin Ajustar");

        pfs.setText("0.0");
        pfs.setEnabled(false);

        puntos_aj.setText("Puntos de Función Ajustados");

        fc.setText("0.0");
        fc.setEnabled(false);

        factor_c.setText("Factor de Complejidad");

        pfa.setText("0.0");
        pfa.setEnabled(false);

        lines.setText("LDC - Lineas de código");

        ldc.setText("0.0");
        ldc.setEnabled(false);

        miles.setText("KLDC - Miles de lineas de código");

        kldc.setText("0.0");
        kldc.setEnabled(false);

        javax.swing.GroupLayout panel_resultLayout = new javax.swing.GroupLayout(panel_result);
        panel_result.setLayout(panel_resultLayout);
        panel_resultLayout.setHorizontalGroup(
            panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultLayout.createSequentialGroup()
                .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_resultLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(result)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_resultLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_resultLayout.createSequentialGroup()
                                .addComponent(miles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(kldc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_resultLayout.createSequentialGroup()
                                .addComponent(lines)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ldc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_resultLayout.createSequentialGroup()
                                .addComponent(puntos_aj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_resultLayout.createSequentialGroup()
                                .addComponent(factor_c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_resultLayout.createSequentialGroup()
                                .addComponent(pf_s)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfs, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panel_resultLayout.setVerticalGroup(
            panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultLayout.createSequentialGroup()
                .addComponent(result)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_s)
                    .addComponent(pfs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factor_c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntos_aj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lines))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kldc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miles))
                .addGap(50, 50, 50))
        );

        scroll.setViewportView(panel_result);

        volver.setText("< Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_leng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(parametros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(complejidad)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(significativos)
                            .addComponent(consultas)
                            .addComponent(archivos_i)
                            .addComponent(entradas)
                            .addComponent(archivos_l)
                            .addComponent(salidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_co, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(baja)
                                .addGap(40, 40, 40)
                                .addComponent(media)
                                .addGap(29, 29, 29)
                                .addComponent(alta)
                                .addGap(21, 21, 21))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo)
                        .addGap(23, 23, 23)
                        .addComponent(volver))
                    .addComponent(panel_carac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(volver))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parametros)
                    .addComponent(complejidad))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(significativos)
                    .addComponent(baja)
                    .addComponent(media)
                    .addComponent(alta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(entradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salidad)
                        .addGap(18, 18, 18)
                        .addComponent(archivos_l)
                        .addGap(20, 20, 20)
                        .addComponent(archivos_i)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultas))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_co, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(panel_leng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panel_carac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_bActionPerformed

    private void e_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_mActionPerformed

    private void e_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_aActionPerformed

    private void lenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenguajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lenguajeActionPerformed

    private void e_bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e_bFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_e_bFocusLost

    private void lenguajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lenguajeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lenguajeItemStateChanged

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ItemStateChanged

    private void otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otroActionPerformed

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FocusLost

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puntos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel alta;
    private javax.swing.JLabel archivos_i;
    private javax.swing.JLabel archivos_l;
    private javax.swing.JLabel baja;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c10;
    private javax.swing.JComboBox<String> c11;
    private javax.swing.JComboBox<String> c12;
    private javax.swing.JComboBox<String> c13;
    private javax.swing.JComboBox<String> c14;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JComboBox<String> c6;
    private javax.swing.JComboBox<String> c7;
    private javax.swing.JComboBox<String> c8;
    private javax.swing.JComboBox<String> c9;
    private javax.swing.JTextField c_a;
    private javax.swing.JTextField c_b;
    private javax.swing.JTextField c_m;
    private javax.swing.JLabel caracteristicas;
    private javax.swing.JLabel complejidad;
    private javax.swing.JLabel consultas;
    private javax.swing.JTextField e_a;
    private javax.swing.JTextField e_b;
    private javax.swing.JTextField e_m;
    private javax.swing.JLabel entradas;
    private javax.swing.JLabel factor_c;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField i_a;
    private javax.swing.JTextField i_b;
    private javax.swing.JTextField i_m;
    private javax.swing.JTextField kldc;
    private javax.swing.JTextField l_a;
    private javax.swing.JTextField l_b;
    private javax.swing.JLabel l_c1;
    private javax.swing.JLabel l_c10;
    private javax.swing.JLabel l_c11;
    private javax.swing.JLabel l_c12;
    private javax.swing.JLabel l_c13;
    private javax.swing.JLabel l_c14;
    private javax.swing.JLabel l_c2;
    private javax.swing.JLabel l_c3;
    private javax.swing.JLabel l_c4;
    private javax.swing.JLabel l_c5;
    private javax.swing.JLabel l_c6;
    private javax.swing.JLabel l_c7;
    private javax.swing.JLabel l_c8;
    private javax.swing.JLabel l_c9;
    private javax.swing.JTextField l_m;
    private javax.swing.JTextField ldc;
    private javax.swing.JComboBox<String> lenguaje;
    private javax.swing.JLabel lenguaje_de;
    private javax.swing.JLabel lines;
    private javax.swing.JLabel media;
    private javax.swing.JLabel miles;
    private javax.swing.JTextField otro;
    private javax.swing.JPanel panel_carac;
    private javax.swing.JPanel panel_co;
    private javax.swing.JPanel panel_leng;
    private javax.swing.JPanel panel_result;
    private javax.swing.JLabel parametros;
    private javax.swing.JLabel pf_s;
    private javax.swing.JTextField pfa;
    private javax.swing.JTextField pfs;
    private javax.swing.JLabel puntos_aj;
    private javax.swing.JLabel result;
    private javax.swing.JTextField s_a;
    private javax.swing.JTextField s_b;
    private javax.swing.JTextField s_m;
    private javax.swing.JLabel salidad;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel significativos;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
